# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0005_tweetmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetModel',
        ),
    ]
